import re


NORMALIZATION_MAP = {
    "react.js": "react",
    "reactjs": "react",
    "node.js": "node",
    "nodejs": "node",
    "typescript": "typescript",
    "ts": "typescript",
    "javascript": "javascript",
    "js": "javascript",
    "python3": "python",
    "py": "python",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "aws": "aws",
    "amazon web services": "aws",
    "gcp": "gcp",
    "google cloud platform": "gcp",
    "google cloud": "gcp",
    "azure": "azure",
    "microsoft azure": "azure",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "ci/cd": "ci/cd",
    "continuous integration": "ci/cd",
    "rest api": "rest api",
    "restful api": "rest api",
    "rest": "rest api",
    "graphql": "graphql",
    "sql": "sql",
    "nosql": "nosql",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "redis": "redis",
    "elasticsearch": "elasticsearch",
    "elastic": "elasticsearch",
    "machine learning": "machine learning",
    "ml": "machine learning",
    "artificial intelligence": "artificial intelligence",
    "ai": "artificial intelligence",
    "deep learning": "deep learning",
    "nlp": "nlp",
    "natural language processing": "nlp",
    "agile": "agile",
    "scrum": "scrum",
    "kanban": "kanban",
    "jira": "jira",
    "confluence": "confluence",
    "figma": "figma",
    "adobe xd": "adobe xd",
    "photoshop": "photoshop",
    "illustrator": "illustrator",
    "html": "html",
    "html5": "html",
    "css": "css",
    "css3": "css",
    "tailwind": "tailwind",
    "tailwindcss": "tailwind",
    "tailwind css": "tailwind",
    "bootstrap": "bootstrap",
    "sass": "sass",
    "scss": "sass",
    "less": "less",
    "webpack": "webpack",
    "vite": "vite",
    "babel": "babel",
    "eslint": "eslint",
    "prettier": "prettier",
    "jest": "jest",
    "pytest": "pytest",
    "cypress": "cypress",
    "selenium": "selenium",
    "playwright": "playwright",
    "next.js": "next.js",
    "nextjs": "next.js",
    "vue.js": "vue",
    "vuejs": "vue",
    "vue": "vue",
    "angular": "angular",
    "angular.js": "angular",
    "angularjs": "angular",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "express": "express",
    "express.js": "express",
    "spring": "spring",
    "spring boot": "spring boot",
    "laravel": "laravel",
    "ruby on rails": "ruby on rails",
    "rails": "ruby on rails",
    "asp.net": "asp.net",
    "dotnet": "asp.net",
    ".net": "asp.net",
    "c#": "c#",
    "csharp": "c#",
    "java": "java",
    "kotlin": "kotlin",
    "swift": "swift",
    "objective-c": "objective-c",
    "rust": "rust",
    "go": "go",
    "golang": "go",
    "ruby": "ruby",
    "php": "php",
    "scala": "scala",
    "r": "r",
    "matlab": "matlab",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "scikit-learn": "scikit-learn",
    "pandas": "pandas",
    "numpy": "numpy",
    "matplotlib": "matplotlib",
    "opencv": "opencv",
    "linux": "linux",
    "unix": "unix",
    "bash": "bash",
    "shell": "bash",
    "powershell": "powershell",
    "terraform": "terraform",
    "ansible": "ansible",
    "jenkins": "jenkins",
    "circleci": "circleci",
    "github actions": "github actions",
    "datadog": "datadog",
    "new relic": "new relic",
    "grafana": "grafana",
    "prometheus": "prometheus",
    "splunk": "splunk",
    "tableau": "tableau",
    "power bi": "power bi",
    "looker": "looker",
    "salesforce": "salesforce",
    "sap": "sap",
    "oracle": "oracle",
    "mysql": "mysql",
    "mariadb": "mariadb",
    "sqlite": "sqlite",
    "dynamodb": "dynamodb",
    "cassandra": "cassandra",
    "neo4j": "neo4j",
    "rabbitmq": "rabbitmq",
    "kafka": "kafka",
    "apache kafka": "kafka",
    "spark": "spark",
    "apache spark": "spark",
    "hadoop": "hadoop",
    "airflow": "airflow",
    "dbt": "dbt",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "redshift": "redshift",
    "s3": "s3",
    "ec2": "ec2",
    "lambda": "lambda",
    "ecs": "ecs",
    "eks": "eks",
    "iam": "iam",
    "cloudformation": "cloudformation",
    "cdk": "cdk",
    "microservices": "microservices",
    "micro-services": "microservices",
    "soa": "soa",
    "event-driven": "event-driven",
    "event driven": "event-driven",
    "serverless": "serverless",
    "monolith": "monolith",
    "mvc": "mvc",
    "mvvm": "mvvm",
    "oop": "oop",
    "functional programming": "functional programming",
    "fp": "functional programming",
    "tdd": "tdd",
    "test driven development": "tdd",
    "bdd": "bdd",
    "ddd": "ddd",
    "domain driven design": "ddd",
    "clean architecture": "clean architecture",
    "hexagonal architecture": "hexagonal architecture",
    "ports and adapters": "hexagonal architecture",
    "solid": "solid",
    "design patterns": "design patterns",
    "system design": "system design",
    "distributed systems": "distributed systems",
    "high availability": "high availability",
    "scalability": "scalability",
    "performance optimization": "performance optimization",
    "security": "security",
    "owasp": "owasp",
    "penetration testing": "penetration testing",
    "pentesting": "penetration testing",
    "encryption": "encryption",
    "oauth": "oauth",
    "oauth2": "oauth",
    "oauth 2.0": "oauth",
    "jwt": "jwt",
    "saml": "saml",
    "sso": "sso",
    "single sign-on": "sso",
    "ldap": "ldap",
    "active directory": "active directory",
    "communication": "communication",
    "teamwork": "teamwork",
    "collaboration": "collaboration",
    "leadership": "leadership",
    "problem solving": "problem solving",
    "problem-solving": "problem solving",
    "critical thinking": "critical thinking",
    "analytical thinking": "analytical thinking",
    "time management": "time management",
    "project management": "project management",
    "stakeholder management": "stakeholder management",
    "mentoring": "mentoring",
    "coaching": "coaching",
    "presentation": "presentation",
    "public speaking": "public speaking",
    "writing": "writing",
    "documentation": "documentation",
    "attention to detail": "attention to detail",
    "detail-oriented": "attention to detail",
    "self-motivated": "self-motivated",
    "self motivated": "self-motivated",
    "proactive": "proactive",
    "adaptability": "adaptability",
    "flexibility": "adaptability",
    "creativity": "creativity",
    "innovation": "innovation",
    "initiative": "initiative",
    "decision making": "decision making",
    "decision-making": "decision making",
    "conflict resolution": "conflict resolution",
    "negotiation": "negotiation",
    "empathy": "empathy",
    "emotional intelligence": "emotional intelligence",
    "customer focus": "customer focus",
    "customer-oriented": "customer focus",
    "results-oriented": "results-oriented",
    "results oriented": "results-oriented",
    "multitasking": "multitasking",
    "cross-functional": "cross-functional",
    "cross functional": "cross-functional",
}


def normalize_skill(skill: str) -> str:
    cleaned = skill.strip().lower()
    cleaned = re.sub(r"[^a-z0-9\s\#\.\-\/]", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return NORMALIZATION_MAP.get(cleaned, cleaned)


def normalize_skills_list(skills: list[str]) -> list[str]:
    seen = set()
    result = []
    for skill in skills:
        normalized = normalize_skill(skill)
        if normalized not in seen:
            seen.add(normalized)
            result.append(normalized)
    return result


def find_skill_matches(user_skills: list[str], required_skills: list[str]) -> list[dict]:
    normalized_user = {normalize_skill(s): s for s in user_skills}
    normalized_required = {normalize_skill(s): s for s in required_skills}

    matches = []
    for norm_key, original in normalized_required.items():
        matched = norm_key in normalized_user
        matches.append({
            "name": original,
            "normalized": norm_key,
            "matched": matched,
            "user_version": normalized_user.get(norm_key),
        })

    return matches
